// Généré par scripts/extract-destiny-symbols.mjs — ne pas modifier à la main.
//
// Points de code des symboles du jeu, tels qu'ils sont nommés dans
// public/fonts/destiny_symbols_common.otf et destiny_symbols_pc.otf.
// 389 glyphes, dont 37 calques.

/** Caractère de chaque symbole, indexé par le nom que lui donne la police. */
export const DESTINY_GLYPHS = {
  superscript_r: "\u036C",
  saison: "\u1D49",
  s_mark: "\uE050",
  capital_eszet: "\uE051",
  light: "\uE052",
  small_blocker: "\uE053",
  medium_blocker: "\uE054",
  large_blocker: "\uE055",
  healing_sword: "\uE056",
  void_blades: "\uE057",
  meteor_strike: "\uE058",
  settings: "\uE059",
  thermal_maul: "\uE060",
  void_shield: "\uE061",
  thermal_knives: "\uE062",
  arc_staff: "\uE063",
  nova_pulse: "\uE064",
  arc_beam: "\uE065",
  valkyrie: "\uE066",
  hammer_throw_melee: "\uE067",
  xl_blocker: "\uE068",
  invasion: "\uE069",
  combat_role_pierce: "\uE070",
  combat_role_overload: "\uE071",
  combat_role_stagger: "\uE072",
  quest: "\uE075",
  stasis_key_0: "\uE076",
  stasis_key_1: "\uE077",
  stasis_key_03: "\uE078",
  stasis_key_3: "\uE079",
  stasis_grenade_bolt: "\uE080",
  stasis_grenade_flare: "\uE081",
  stasis_grenade_wave: "\uE082",
  stasis_titan_super: "\uE083",
  stasis_hunter_super: "\uE084",
  stasis_warlock_super: "\uE085",
  stasis_titan_melee: "\uE086",
  stasis_hunter_melee: "\uE087",
  stasis_warlock_melee: "\uE088",
  stasis_encasement_shatter: "\uE089",
  stasis_crystal_shatter: "\uE090",
  stasis_turret: "\uE091",
  stasis_titan_spear: "\uE092",
  void_soul: "\uE093",
  balloom: "\uE094",
  void_shield_throw: "\uE095",
  void_ball: "\uE096",
  void_quickfall: "\uE097",
  bow: "\uE099",
  auto_rifle: "\uE100",
  pulse_rifle: "\uE101",
  scout_rifle: "\uE102",
  hand_cannon: "\uE103",
  shotgun: "\uE104",
  sniper_rifle: "\uE105",
  fusion_rifle: "\uE106",
  smg: "\uE107",
  rocket_launcher: "\uE108",
  sidearm: "\uE109",
  melee: "\uE110",
  grenade: "\uE111",
  hunter_smoke: "\uE112",
  grenade_launcher: "\uE113",
  solar_hammer_slam: "\uE114",
  solar_dynamite: "\uE115",
  solar_blast: "\uE116",
  arc_drone: "\uE118",
  warlock_blade: "\uE119",
  nova_bomb: "\uE120",
  hunter_staff: "\uE121",
  fist_of_havoc: "\uE122",
  golden_gun: "\uE123",
  throwing_knife: "\uE124",
  arc_warlock_super: "\uE125",
  solar_tian_super: "\uE126",
  void_hunter_super: "\uE127",
  void_titan_super: "\uE128",
  turret: "\uE130",
  pike: "\uE131",
  interceptor: "\uE132",
  sparrow: "\uE133",
  shield_artifact: "\uE134",
  loader_tank: "\uE135",
  spear_launcher: "\uE136",
  guardian_tank: "\uE137",
  beam_weapon: "\uE138",
  stasis: "\uE139",
  thermal: "\uE140",
  environment_hazard: "\uE141",
  headshot: "\uE142",
  arc: "\uE143",
  void: "\uE144",
  lostsector: "\uE145",
  revive_token: "\uE146",
  gilded_title: "\uE147",
  "UniFFFD.001": "\uE148",
  cabal_rifle: "\uE150",
  shrapnel_launcher: "\uE151",
  wire_rifle: "\uE152",
  sword_heavy: "\uE153",
  machinegun: "\uE154",
  grenade_launcher_field_forged: "\uE155",
  glaive: "\uE156",
  tofu: "\uEEFA",
  arc_titan_melee2: "\uEEFB",
  arc_warlock_aspect: "\uEEFC",
  arc_hunter_super: "\uEEFD",
  arc_jolt: "\uEEFE",
  strand_threadling: "\uEEFF",
  strand_infest: "\uEF00",
  strand_tangle: "\uEF01",
  strand_suspend_grenade: "\uEF02",
  strand_threadling_grenade: "\uEF03",
  strand_grappling_hook: "\uEF04",
  strand_grappling_hook_melee: "\uEF05",
  strand_rope_dart_melee: "\uEF06",
  strand_severing_leap_melee: "\uEF07",
  strand_seize_melee: "\uEF08",
  strand_hunter_quickfall: "\uEF09",
  strand_titan_suspend_brace: "\uEF0A",
  strand_rope_dart_super: "\uEF0B",
  strand_titan_berserker_super: "\uEF0C",
  strand_warlock_minion_super: "\uEF0D",
  strand_kill: "\uEF0E",
  emoji_standard_background: "\uEF0F", // calque
  emoji_dotted_eyes: "\uEF10",
  emoji_curled_eyes: "\uEF11",
  emoji_linear_eyes: "\uEF12",
  emoji_shocked_inner_eyes: "\uEF13",
  emoji_shocked_outer_eyes: "\uEF14", // calque
  emoji_smile_mouth: "\uEF15", // calque
  emoji_excited_mouth: "\uEF16", // calque
  emoji_upperteeth_mouth: "\uEF17", // calque
  emoji_lowerrteeth_mouth: "\uEF18", // calque
  emoji_tongue_mouth: "\uEF19", // calque
  emoji_grimacing_mouth: "\uEF1A", // calque
  emoji_grimacingteeth_mouth: "\uEF1B", // calque
  emoji_shocked_mouth: "\uEF1C", // calque
  emoji_traits_freezing: "\uEF1D", // calque
  emoji_traits_loving: "\uEF1E", // calque
  emoji_traits_crying: "\uEF1F", // calque
  emoji_traits_blushing: "\uEF20", // calque
  emoji_symbols_heart: "\uEF21",
  emoji_symbols_flowerpetals: "\uEF22", // calque
  emoji_symbols_flowercenter: "\uEF23", // calque
  emoji_symbols_flowerleaves: "\uEF24",
  emoji_hands_waving: "\uEF25", // calque
  emoji_hands_waving_detail: "\uEF26",
  emoji_hands_clapping: "\uEF27", // calque
  emoji_hands_clapping_otherhand: "\uEF28", // calque
  emoji_hands_clapping_details: "\uEF29",
  emoji_hands_flexing: "\uEF2A", // calque
  emoji_hands_flexing_details: "\uEF2B",
  strand_warlock_suspend_tangle: "\uEF2C",
  strand_hunter_clone: "\uEF2D",
  strand_titan_slide_melee: "\uEF2E",
  region_chest: "\uEF2F",
  strand_hunter_buzzsaw: "\uEF30",
  void_titan_exotic_chest: "\uEF31",
  arc_hunter_air_move: "\uEF32",
  arc_hunter_blink_dagger: "\uEF33",
  solar_drone: "\uEF34",
  solar_warlock_phoenix_form: "\uEF35",
  void_titan_axe_throw: "\uEF36",
  void_titan_axe_throw_relic: "\uEF37",
  void_titan_grenade_absorb_blast: "\uEF38",
  prism_titan_grenade: "\uEF39",
  prism_hunter_grenade: "\uEF3A",
  prism_warlock_grenade: "\uEF3B",
  light_ability: "\uEF3C",
  darkness_ability: "\uEF3D",
  roster: "\uEF3E",
  timer: "\uEF3F",
  matterball: "\uEF40",
  translator: "\uEF41",
  relocator: "\uEF42",
  bender: "\uEF43",
  brig_glyph: "\uEF44",
  crossbow: "\uEF45",
  bonus_drop_engram: "\uEF46",
  prismatic: "\uEF47",
  solar_titan_brace_detonator: "\uEF48",
  void_warlock_void_pull: "\uEF49",
  hunter_void_dash: "\uEF50",
  solar_hunter_deadshot_dodge: "\uEF51",
  stasis_flux: "\uEF52",
  strand_pulse: "\uEF53",
  UniFFFD: "\uFFFD",
  french_space: "\u202F",
  x_Button: "\uE000",
  circle_Button: "\uE001",
  square_Button: "\uE002",
  triangle_Button: "\uE003",
  start_button: "\uE004",
  select_button: "\uE005",
  right_trigger: "\uE006",
  l2_button: "\uE007",
  l1_button: "\uE008",
  r1_button: "\uE009",
  right_stick: "\uE010",
  Right_Click: "\uE011",
  left_stick: "\uE012",
  left_click: "\uE013",
  dpad_up: "\uE014",
  dpad_right: "\uE015",
  dpad_down: "\uE016",
  dpad_left: "\uE017",
  Share: "\uE018",
  Options: "\uE019",
  black_background: "\uE020", // calque
  touch_background: "\uE021", // calque
  dpad_all_ps4: "\uE022",
  dpad_left_right: "\uE023",
  dpad_up_down: "\uE024",
  ps4_x_Button: "\uE025",
  ps4_circle_Button: "\uE026",
  ps4_square_Button: "\uE027",
  ps4_triangle_Button: "\uE028",
  ps4_start_button: "\uE029",
  ps4_select_button: "\uE030",
  "right_trigger.002": "\uE031",
  "l2_button.001": "\uE032",
  "l1_button.001": "\uE033",
  "r1_button.001": "\uE034",
  "right_stick.001": "\uE035",
  "Right_Click.002": "\uE036",
  "left_stick.002": "\uE037",
  "left_click.002": "\uE038",
  "dpad_up.002": "\uE039",
  "dpad_right.002": "\uE040",
  "dpad_down.002": "\uE041",
  "dpad_left.002": "\uE042",
  "Options.001": "\uE044",
  "black_background.002": "\uE045", // calque
  ps4_touch_background: "\uE046", // calque
  ps4_dpad_all: "\uE047",
  ps4_dpad_left_right: "\uE048",
  ps4_dpad_up_down: "\uE049",
  dpad_left_right_xbox: "\uE157",
  dpad_up_down_xbox: "\uE158",
  dpad_all_xbox: "\uE159",
  A_Button: "\uE160",
  B_Button: "\uE161",
  X_Button: "\uE162",
  Y_Button: "\uE163",
  menu_button: "\uE164",
  view_button: "\uE165",
  "right_trigger.001": "\uE166",
  LB: "\uE167",
  RB: "\uE168",
  Right_Stick: "\uE169",
  "Right_Click.001": "\uE170",
  "left_stick.001": "\uE171",
  "left_click.001": "\uE172",
  "dpad_up.001": "\uE173",
  "dpad_right.001": "\uE174",
  "dpad_down.001": "\uE175",
  "dpad_left.001": "\uE176",
  "black_background.001": "\uE177", // calque
  burger_background: "\uE178", // calque
  back_button_360: "\uE179",
  start_button_360: "\uE180",
  left_trigger: "\uE181",
  n_tilde: "\uE182",
  ordinal_indicator: "\uE183",
  z_dot: "\uE184",
  s_acute: "\uE185",
  l_stroke: "\uE186",
  a_ogonek: "\uE187",
  o_acute: "\uE188",
  superscript2: "\uE202",
  pound: "\uE204",
  diaeresis: "\uE205",
  micro: "\uE206",
  O_diaeresis: "\uE208",
  A_diaeresis: "\uE209",
  broken_bar: "\uE211",
  inverted_exclamation: "\uE212",
  inverted_question: "\uE213",
  I_grave: "\uE214",
  E_grave: "\uE215",
  E_acute: "\uE216",
  sharp_s: "\uE217",
  C_cedilla: "\uE218",
  O_grave: "\uE219",
  A_grave: "\uE220",
  U_grave: "\uE221",
  nintendo_a_Button: "\uE230",
  nintendo_b_Button: "\uE231",
  nintendo_x_Button: "\uE232",
  nintendo_y_Button: "\uE233",
  nintendo_start_button: "\uE234",
  nintendo_select_button: "\uE235",
  nintendo_right_trigger: "\uE236",
  nintendo_l2_button: "\uE237",
  nintendo_l1_button: "\uE238",
  nintendo_r1_button: "\uE239",
  nintendo_right_stick: "\uE240",
  nintendo_Right_Click: "\uE241",
  nintendo_left_stick: "\uE242",
  nintendo_left_click: "\uE243",
  nintendo_dpad_up: "\uE244",
  nintendo_dpad_right: "\uE245",
  nintendo_dpad_down: "\uE246",
  nintendo_dpad_left: "\uE247",
  nintendo_Share: "\uE248",
  nintendo_Options: "\uE249",
  nintendo_black_background: "\uE250", // calque
  nintendo_touch_background: "\uE251", // calque
  nintendo_dpad_all: "\uE252",
  nintendo_dpad_left_right: "\uE253",
  nintendo_dpad_up_down: "\uE254",
  nbspace: "\uEEA0",
  spacebar: "\uEEA1",
  printScreen: "\uEEA2",
  ScrollLock: "\uEEA3",
  Pause: "\uEEA4",
  backspace: "\uEEA5",
  tab: "\uEEA6",
  caps_lock: "\uEEA7",
  return: "\uEEA8",
  shift_left: "\uEEA9",
  shift_right: "\uEEAA",
  ctrl_left: "\uEEAB",
  windows: "\uEEAC",
  alt_left: "\uEEAD",
  alt_right: "\uEEAE",
  windows_right: "\uEEAF",
  menu: "\uEEB0",
  ctrl_right: "\uEEB1",
  up: "\uEEB2",
  down: "\uEEB3",
  left: "\uEEB4",
  right: "\uEEB5",
  insert: "\uEEB6",
  home: "\uEEB7",
  page_up: "\uEEB8",
  delete: "\uEEB9",
  end: "\uEEBA",
  Page_down: "\uEEBB",
  numlock: "\uEEBC",
  num_divide: "\uEEBD",
  num_multiply: "\uEEBE",
  num_0: "\uEEBF",
  num_1: "\uEEC0",
  num_2: "\uEEC1",
  num_3: "\uEEC2",
  num_4: "\uEEC3",
  num_5: "\uEEC4",
  num_6: "\uEEC5",
  num_7: "\uEEC6",
  num_8: "\uEEC7",
  num_9: "\uEEC8",
  num_subtract: "\uEEC9",
  num_add: "\uEECA",
  num_enter: "\uEECB",
  num_decimal: "\uEECC",
  mouse1: "\uEECD",
  mouse2: "\uEECE",
  mouse3: "\uEECF",
  mouse4: "\uEED0",
  mouse5: "\uEED1",
  mousewheel_up: "\uEED2",
  mousewheel_down: "\uEED3",
  F1: "\uEED4",
  F2: "\uEED5",
  F3: "\uEED6",
  F4: "\uEED7",
  F5: "\uEED8",
  F6: "\uEED9",
  key_escape: "\uEEDA",
  umlaut: "\uEEDC",
  forward_slash: "\uEEDF",
  F7: "\uEEE0",
  F8: "\uEEE1",
  F9: "\uEEE2",
  F10: "\uEEE3",
  F11: "\uEEE4",
  F12: "\uEEE5",
  key_bind: "\uEEE6",
  standard_backing: "\uEEF0", // calque
  large_backing: "\uEEF1", // calque
  mouse1_button: "\uEEF3", // calque
  mouse2_button: "\uEEF4", // calque
  mouse3_button: "\uEEF5", // calque
  mouse4_button: "\uEEF6", // calque
  mouse5_button: "\uEEF7", // calque
  mousewheel_up_button: "\uEEF8", // calque
  mousewheel_down_button: "\uEEF9", // calque
} as const;

export type DestinyGlyphName = keyof typeof DESTINY_GLYPHS;

/**
 * Glyphes de chasse nulle : ils ne valent rien seuls et se superposent à un
 * autre glyphe (fond de touche, bouton de souris éclairé…).
 */
export const DESTINY_OVERLAY_GLYPHS: ReadonlySet<string> = new Set([
  "emoji_standard_background",
  "emoji_shocked_outer_eyes",
  "emoji_smile_mouth",
  "emoji_excited_mouth",
  "emoji_upperteeth_mouth",
  "emoji_lowerrteeth_mouth",
  "emoji_tongue_mouth",
  "emoji_grimacing_mouth",
  "emoji_grimacingteeth_mouth",
  "emoji_shocked_mouth",
  "emoji_traits_freezing",
  "emoji_traits_loving",
  "emoji_traits_crying",
  "emoji_traits_blushing",
  "emoji_symbols_flowerpetals",
  "emoji_symbols_flowercenter",
  "emoji_hands_waving",
  "emoji_hands_clapping",
  "emoji_hands_clapping_otherhand",
  "emoji_hands_flexing",
  "black_background",
  "touch_background",
  "black_background.002",
  "ps4_touch_background",
  "black_background.001",
  "burger_background",
  "nintendo_black_background",
  "nintendo_touch_background",
  "standard_backing",
  "large_backing",
  "mouse1_button",
  "mouse2_button",
  "mouse3_button",
  "mouse4_button",
  "mouse5_button",
  "mousewheel_up_button",
  "mousewheel_down_button",
]);
